version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci

  pre_build:
    commands:
      - echo "Setting up environment variables..."
      - export CDK_DEFAULT_ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
      - export CDK_DEFAULT_REGION=us-east-1
      - export GITHUB_REPO=Stacy-JoyM/aws-cdk-workflow-capstone4
      - export GITHUB_CONNECTION_ARN=arn:aws:codeconnections:us-east-1:654129064706:connection/ea5920fc-a126-4814-ae30-0563bd906aba
      - echo "Environment variables set:"
      - echo "  CDK_DEFAULT_ACCOUNT=$CDK_DEFAULT_ACCOUNT"
      - echo "  CDK_DEFAULT_REGION=$CDK_DEFAULT_REGION"
      - echo "  GITHUB_REPO=$GITHUB_REPO"
      - echo "  GITHUB_CONNECTION_ARN=$GITHUB_CONNECTION_ARN"

  build:
    commands:
      - echo "Building the project..."
      - npm run build
      - echo "Synthesizing CDK..."
      - npx cdk synth --no-version-reporting --no-asset-metadata --quiet

artifacts:
  files:
    - '**/*'
  base-directory: cdk.out
